'use client';

import { useState } from 'react';
import type { AnalysisResult, Finding } from '../lib/solidity-analyzer';

function severityColor(severity: 'high' | 'medium' | 'low'): string {
  switch (severity) {
    case 'high': return 'border-red-300 dark:border-red-700 bg-red-50 dark:bg-red-900/20 text-red-800 dark:text-red-200';
    case 'medium': return 'border-yellow-300 dark:border-yellow-700 bg-yellow-50 dark:bg-yellow-900/20 text-yellow-800 dark:text-yellow-200';
    case 'low': return 'border-blue-300 dark:border-blue-700 bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-200';
  }
}

function severityBadge(severity: 'high' | 'medium' | 'low'): string {
  switch (severity) {
    case 'high': return 'bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-300';
    case 'medium': return 'bg-yellow-100 dark:bg-yellow-900/40 text-yellow-700 dark:text-yellow-300';
    case 'low': return 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300';
  }
}

function FindingList({ findings, title }: { findings: Finding[]; title: string }) {
  const [open, setOpen] = useState(true);

  if (findings.length === 0) return null;

  return (
    <div className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-4 py-3 bg-gray-50 dark:bg-gray-800 text-left font-medium text-gray-900 dark:text-white"
      >
        <span>{title} ({findings.length})</span>
        <span className={`transform transition-transform ${open ? 'rotate-180' : ''}`}>▼</span>
      </button>
      {open && (
        <div className="divide-y divide-gray-200 dark:divide-gray-700">
          {findings.map((finding, idx) => (
            <div key={idx} className={`p-4 ${severityColor(finding.severity)}`}>
              <div className="flex items-start justify-between mb-1">
                <div className="flex items-center gap-2">
                  <span className={`text-xs font-semibold px-2 py-0.5 rounded ${severityBadge(finding.severity)}`}>
                    {finding.severity.toUpperCase()}
                  </span>
                  {finding.line !== null && (
                    <span className="text-xs font-mono text-gray-500 dark:text-gray-400">Line {finding.line}</span>
                  )}
                </div>
              </div>
              <p className="text-sm font-medium mb-1">{finding.message}</p>
              <p className="text-xs opacity-80">{finding.suggestion}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function generateMarkdown(result: AnalysisResult): string {
  const lines: string[] = [
    '# Solidity Contract Analysis Report',
    '',
    `**Arc Compatibility Score**: ${result.score}/100`,
    '',
    '---',
    '',
  ];

  if (result.gasIssues.length > 0) {
    lines.push('## Gas Issues', '');
    for (const f of result.gasIssues) {
      lines.push(`- [${f.severity.toUpperCase()}] ${f.message}${f.line ? ` (line ${f.line})` : ''}`);
      lines.push(`  - *Suggestion*: ${f.suggestion}`);
    }
    lines.push('');
  }

  if (result.securityIssues.length > 0) {
    lines.push('## Security Issues', '');
    for (const f of result.securityIssues) {
      lines.push(`- [${f.severity.toUpperCase()}] ${f.message}${f.line ? ` (line ${f.line})` : ''}`);
      lines.push(`  - *Suggestion*: ${f.suggestion}`);
    }
    lines.push('');
  }

  if (result.arcPatterns.length > 0) {
    lines.push('## Arc Patterns Detected', '');
    for (const p of result.arcPatterns) {
      lines.push(`- ✅ ${p}`);
    }
    lines.push('');
  }

  lines.push('---', '', '*Generated by Arc Task Verifier Bot — Solidity Analyzer*');
  return lines.join('\n');
}

export default function ContractAnalyzer() {
  const [code, setCode] = useState('');
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleAnalyze = async () => {
    if (!code.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch('/api/analyze-contract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Analysis failed');
      }

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  };

  const handleCopyMarkdown = () => {
    if (!result) return;
    const md = generateMarkdown(result);
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const hasIssues = result && (result.gasIssues.length > 0 || result.securityIssues.length > 0);

  const codeLength = new TextEncoder().encode(code).length;

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-2">
        <label htmlFor="solidity-code" className="text-sm font-medium text-gray-700 dark:text-gray-300">
          Paste Solidity source code
        </label>
        <textarea
          id="solidity-code"
          value={code}
          onChange={(e) => {
            if (new TextEncoder().encode(e.target.value).length <= 50_000) {
              setCode(e.target.value);
            }
          }}
          className="w-full h-64 p-3 font-mono text-sm border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder={`// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract MyContract {\n    ...\n}`}
          spellCheck={false}
        />
        <div className="flex items-center justify-between">
          <span className="text-xs text-gray-500 dark:text-gray-400">
            {codeLength.toLocaleString()} / 50,000 bytes
          </span>
          <button
            type="button"
            onClick={handleAnalyze}
            disabled={loading || !code.trim()}
            className="px-4 py-2 bg-indigo-600 text-white text-sm rounded-md hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? 'Analyzing...' : 'Analyze Contract'}
          </button>
        </div>
      </div>

      {error && (
        <div className="p-3 bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 text-sm rounded-md">
          {error}
        </div>
      )}

      {result && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">Analysis Results</h3>
              {hasIssues ? (
                <span className={`text-lg font-bold font-mono ${result.score >= 70 ? 'text-green-600 dark:text-green-400' : result.score >= 40 ? 'text-yellow-600 dark:text-yellow-400' : 'text-red-600 dark:text-red-400'}`}>
                  {result.score}/100
                </span>
              ) : (
                <span className="text-lg font-bold font-mono text-green-600 dark:text-green-400">
                  {result.score}/100
                </span>
              )}
            </div>
            <button
              type="button"
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 text-sm rounded-md hover:bg-gray-100 dark:hover:bg-gray-700"
            >
              {copied ? 'Copied!' : 'Copy as Markdown'}
            </button>
          </div>

          {!hasIssues && result.arcPatterns.length === 0 && (
            <div className="p-4 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 text-green-700 dark:text-green-300 rounded-md text-sm">
              No issues found. Clean Solidity code.
            </div>
          )}

          <FindingList findings={result.gasIssues} title="⛽ Gas Issues" />
          <FindingList findings={result.securityIssues} title="🔒 Security Issues" />

          {result.arcPatterns.length > 0 && (
            <div className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden">
              <div className="px-4 py-3 bg-gray-50 dark:bg-gray-800 font-medium text-gray-900 dark:text-white">
                🌐 Arc Patterns ({result.arcPatterns.length})
              </div>
              <div className="divide-y divide-gray-200 dark:divide-gray-700">
                {result.arcPatterns.map((pattern, idx) => (
                  <div key={idx} className="px-4 py-3 bg-green-50 dark:bg-green-900/20 text-green-800 dark:text-green-200 text-sm">
                    ✅ {pattern}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
