'use client';

import { useState, useEffect, useCallback } from 'react';
import type { GasEstimate } from '../lib/gas-estimator';
import { MAX_BYTECODE_SIZE } from '../lib/gas-estimator';

export default function GasEstimator({ onAddToReport }: { onAddToReport?: (section: string) => void }) {
  const [mode, setMode] = useState<'deploy' | 'interact'>('deploy');
  const [bytecodeSize, setBytecodeSize] = useState(1000);
  const [hasLoop, setHasLoop] = useState(false);
  const [estimate, setEstimate] = useState<GasEstimate | null>(null);
  const [loading, setLoading] = useState(false);
  const [manualInput, setManualInput] = useState('1000');

  const fetchEstimate = useCallback(async () => {
    setLoading(true);
    try {
      const body = mode === 'deploy'
        ? { bytecodeSize }
        : { functionSig: '0x', hasLoop };

      const response = await fetch('/api/gas-estimate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      if (response.ok) {
        const data = await response.json();
        setEstimate(data);
      }
    } catch {
      // silent fail — estimates degrade gracefully
    } finally {
      setLoading(false);
    }
  }, [mode, bytecodeSize, hasLoop]);

  useEffect(() => {
    const timer = setTimeout(fetchEstimate, 200);
    return () => clearTimeout(timer);
  }, [fetchEstimate]);

  const handleSliderChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = parseInt(e.target.value, 10);
    setBytecodeSize(val);
    setManualInput(val.toString());
  };

  const handleManualInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    const raw = e.target.value.replace(/\D/g, '');
    setManualInput(raw);
    const val = parseInt(raw, 10);
    if (!isNaN(val) && val >= 0 && val <= MAX_BYTECODE_SIZE) {
      setBytecodeSize(val);
    }
  };

  const handleAddToReport = () => {
    if (!estimate || !onAddToReport) return;
    const lines = [
      '## Gas Cost Estimate',
      '',
      `**Mode**: ${mode === 'deploy' ? 'Contract Deployment' : 'Interaction'}`,
      mode === 'deploy' ? `**Bytecode Size**: ${bytecodeSize} bytes` : `**Has Loop**: ${hasLoop ? 'Yes' : 'No'}`,
      `**Estimated Gas**: ${estimate.gasUnits.toLocaleString()} units`,
      `**Estimated USDC Cost**: ${estimate.usdcCost}`,
      '',
      '> ⚠️ Estimates are approximate. Actual costs vary.',
      '',
      '| Component | Gas |',
      '|-----------|-----|',
    ];
    for (const item of estimate.breakdown) {
      lines.push(`| ${item} |`);
    }
    lines.push('');
    lines.push('*Generated by Arc Task Verifier Bot — Gas Estimator*');
    onAddToReport(lines.join('\n'));
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 mb-2">
        <button
          type="button"
          onClick={() => setMode('deploy')}
          className={`px-3 py-1.5 text-sm rounded-md font-medium ${
            mode === 'deploy'
              ? 'bg-indigo-600 text-white'
              : 'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300'
          }`}
        >
          Deployment
        </button>
        <button
          type="button"
          onClick={() => setMode('interact')}
          className={`px-3 py-1.5 text-sm rounded-md font-medium ${
            mode === 'interact'
              ? 'bg-indigo-600 text-white'
              : 'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300'
          }`}
        >
          Interaction
        </button>
      </div>

      {mode === 'deploy' ? (
        <div className="space-y-3">
          <div className="flex items-center gap-3">
            <label className="text-sm text-gray-700 dark:text-gray-300 whitespace-nowrap">
              Contract size (bytes):
            </label>
            <input
              type="text"
              value={manualInput}
              onChange={handleManualInput}
              className="w-24 px-2 py-1 text-sm border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-md font-mono text-center"
            />
            <span className="text-xs text-gray-500">/ {MAX_BYTECODE_SIZE.toLocaleString()} max</span>
          </div>
          <input
            type="range"
            min={0}
            max={MAX_BYTECODE_SIZE}
            value={bytecodeSize}
            onChange={handleSliderChange}
            className="w-full accent-indigo-600"
            aria-label="Contract bytecode size slider"
          />
          <div className="flex justify-between text-xs text-gray-500 dark:text-gray-400">
            <span>0 bytes</span>
            <span>{MAX_BYTECODE_SIZE.toLocaleString()} bytes</span>
          </div>
        </div>
      ) : (
        <label className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300">
          <input
            type="checkbox"
            checked={hasLoop}
            onChange={(e) => setHasLoop(e.target.checked)}
            className="rounded"
          />
          Function contains loops (higher gas cost)
        </label>
      )}

      <div className="p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 text-blue-700 dark:text-blue-300 text-xs rounded-md">
        Arc Testnet uses USDC for gas — no ETH needed.
      </div>

      {loading && !estimate && (
        <div className="text-sm text-gray-500 dark:text-gray-400 animate-pulse">Estimating...</div>
      )}

      {estimate && (
        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <div className="p-3 bg-gray-50 dark:bg-gray-700 rounded-md">
              <p className="text-xs text-gray-500 dark:text-gray-400">Gas Units</p>
              <p className="text-lg font-bold text-gray-900 dark:text-white font-mono">
                {estimate.gasUnits.toLocaleString()}
              </p>
            </div>
            <div className="p-3 bg-green-50 dark:bg-green-900/30 rounded-md">
              <p className="text-xs text-gray-500 dark:text-gray-400">Estimated Cost</p>
              <p className="text-lg font-bold text-green-700 dark:text-green-300 font-mono">
                {estimate.usdcCost}
              </p>
            </div>
          </div>

          <details className="text-sm">
            <summary className="cursor-pointer text-gray-600 dark:text-gray-400 font-medium">
              Breakdown
            </summary>
            <ul className="mt-2 space-y-1 pl-4">
              {estimate.breakdown.map((item, idx) => (
                <li key={idx} className="text-gray-600 dark:text-gray-400 list-disc">{item}</li>
              ))}
            </ul>
          </details>

          <div className="p-2 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 text-yellow-700 dark:text-yellow-300 text-xs rounded-md">
            ⚠️ Estimates are approximate. Actual costs vary.
          </div>

          {onAddToReport && (
            <button
              type="button"
              onClick={handleAddToReport}
              className="px-3 py-1.5 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 text-sm rounded-md hover:bg-gray-100 dark:hover:bg-gray-700"
            >
              Add to Evaluation Report
            </button>
          )}
        </div>
      )}
    </div>
  );
}
