import type { EvaluationResult, Scores } from './types';

export type { EvaluationResult, Scores };

export function generateMarkdownReport(input: string, evaluation: EvaluationResult, scores: Scores): string {
  const date = new Date().toLocaleDateString();

  const appKitSection = evaluation.appkit_details ? `

## App Kit Integration

| Feature | Status |
|---------|--------|
| Send | ${evaluation.appkit_details.has_send ? '✅' : '❌'} |
| Bridge | ${evaluation.appkit_details.has_bridge ? '✅' : '❌'} |
| Swap | ${evaluation.appkit_details.has_swap ? '✅' : '❌'} |
| Unified Balance | ${evaluation.appkit_details.has_unified_balance ? '✅' : '❌'} |
| App Kit Import | ${evaluation.appkit_details.has_appkit_import ? '✅' : '❌'} |
` : '';

  return `# Arc Task Verifier Report

**Generated**: ${date}
**Input**: ${input}

---

## Summary

| Metric | Score |
|--------|-------|
| Signal Score | ${scores.baseSignalScore}/100 |
| Arc Readiness | ${scores.arcBonusScore}/100 |
| **Total Score** | **${scores.totalScore}/100** |
| Category | ${scores.category} |
| Badge | ${scores.badge} |

---

## Core Checks

| Check | Status |
|-------|--------|
| Reproducible | ${evaluation.core_checks.reproducible ? '✅' : '❌'} |
| Setup Steps | ${evaluation.core_checks.has_setup_steps ? '✅' : '❌'} |
| Demo Available | ${evaluation.core_checks.has_demo ? '✅' : '❌'} |
| Dependencies | ${evaluation.core_checks.has_dependencies ? '✅' : '❌'} |

---

## Arc Ecosystem Checks

| Check | Status |
|-------|--------|
| Uses Arc RPC | ${evaluation.arc_checks.uses_arc_rpc ? '✅' : '❌'} |
| Mentions Foundry | ${evaluation.arc_checks.mentions_foundry ? '✅' : '❌'} |
| Smart Contract Ready | ${evaluation.arc_checks.smart_contract_ready ? '✅' : '❌'} |
| USDC Gas Awareness | ${evaluation.arc_checks.uses_usdc_gas_awareness ? '✅' : '❌'} |
| App Kit Usage | ${evaluation.arc_checks.appkit_usage_possible ? '✅' : '❌'} |

---

## Feedback

${evaluation.feedback}${appKitSection}

---

## Missing Items

${evaluation.missing_items.map((item) => `- ${item}`).join('\n')}

---

## Upgrade Path

${evaluation.upgrade_path.map((step, i) => `${i + 1}. ${step}`).join('\n')}

---

*Generated by Arc Task Verifier Bot*
`;
}

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
