export function generateCsvReport(
  evaluations: Array<{ input: string; scores: { baseSignalScore: number; arcBonusScore: number; totalScore: number; badge: string } }>
): string {
  const header = 'URL,Signal Score,Arc Score,Total Score,Badge,Date';
  const rows = evaluations.map(e => {
    const date = new Date().toISOString().split('T')[0];
    return `"${e.input}",${e.scores.baseSignalScore},${e.scores.arcBonusScore},${e.scores.totalScore},"${e.scores.badge}",${date}`;
  });
  return [header, ...rows].join('\n');
}

export function downloadCsv(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generatePdfHtml(
  evaluations: Array<{
    input: string;
    scores: { baseSignalScore: number; arcBonusScore: number; totalScore: number; badge: string; category: string };
    feedback?: string;
  }>
): string {
  const rows = evaluations.map(e => `
    <tr>
      <td>${e.input}</td>
      <td>${e.scores.totalScore}/100</td>
      <td>${e.scores.badge}</td>
      <td>${e.scores.baseSignalScore}</td>
      <td>${e.scores.arcBonusScore}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html>
<html><head><style>
  body { font-family: Arial, sans-serif; margin: 40px; }
  h1 { color: #333; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
  th { background: #4f46e5; color: white; padding: 10px; text-align: left; }
  td { padding: 8px; border-bottom: 1px solid #ddd; }
  .footer { margin-top: 30px; font-size: 12px; color: #666; }
</style></head><body>
  <h1>Arc Task Verifier — Evaluation Report</h1>
  <p>Generated: ${new Date().toLocaleDateString()}</p>
  <table>
    <tr><th>Project</th><th>Score</th><th>Badge</th><th>Signal</th><th>Arc</th></tr>
    ${rows}
  </table>
  <p class="footer">Generated by Arc Task Verifier Bot</p>
</body></html>`;
}
